name: Rebuild on Push

on:
  push:
    branches:
      - main

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run rebuild script
        run: |
          chmod +x ./rebuild.sh
          ./rebuild.sh

